services:
  laminas-app:
    image: shinsenter/laminas:latest
    volumes:
      - .:/var/www/html
      - ./ssl-certs:/etc/ssl/web
    environment:
      TZ: UTC
      PUID: ${UID:-9999}
      PGID: ${GID:-9999}
    ports:
      - "8081:8081"
