<section class="page-content">
    <div class="container jumbotron">
        <!-- registration -->
        <div class="formContainer">
            <div class="row">
                <div class="col-md-6">
                    <div class="box">
                        <h3><span class="fas fa-user"></span>Registration</h3>
                        <?= isset($messages) ? print_r($messages) : '' ?>
                        <?php
                        $email = $userForm->get('Email');
                        $email->setAttribute('class', 'form-control');
                        $email->setAttribute('placeholder', 'Email');

                        $username = $userForm->get('Username');
                        $username->setAttribute('class', 'form-control');
                        $username->setAttribute('placeholder', 'Username');

                        $password = $userForm->get('Password');
                        $password->setAttribute('class', 'form-control');
                        $password->setAttribute('placeholder', 'Mật khẩu');

                        $confirmPassword = $userForm->get('confirm_password');
                        $confirmPassword->setAttribute('class', 'form-control');
                        $confirmPassword->setAttribute('placeholder', 'Xác nhận mật khẩu');

                        $userForm->prepare();
                        echo $this->form()->openTag($userForm);
                        ?>
                        <div class="form-group">
                            <?= $this->formLabel($email); ?>
                            <?= $this->formElement($email); ?>
                            <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
                        </div>
                        <br />
                        <div class="form-group">
                            <?= $this->formLabel($username); ?>
                            <?= $this->formElement($username); ?>
                            <?= $this->formElementErrors()->render($username, ['class' => 'help-block']) ?>
                        </div>
                        <br />
                        <div class="form-group">
                            <?= $this->formLabel($password); ?>
                            <?= $this->formElement($password); ?>
                            <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
                        </div>
                        <br />
                        <div class="form-group">
                            <?= $this->formLabel($confirmPassword); ?>
                            <?= $this->formElement($confirmPassword); ?>
                            <?= $this->formElementErrors()->render($confirmPassword, ['class' => 'help-block']) ?>
                        </div>
                        <br />
                        <?php
                        echo $this->formHidden($userForm->get('user_csrf'));
                        echo $this->formSubmit($userForm->get('submit'));
                        echo $this->form()->closeTag();
                        ?>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="alert alert-info">
                        Fill all the form fileds, to register as new user to the website.
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>