<section class="page-content">
    <div class="container jumbotron">
        <!-- login -->
        <div class="formContainer">
            <div class="row">
                <div class="col-md-6">
                    <div class="box">
                        <h3><span class="fas fa-lock"></span>Login</h3>
                        <?php isset($messages) ? print_r($messages) : '' ?>
                        <?php
                        $email = $form->get('login_fieldset')->get('Email');
                        $email->setAttribute('class', 'form-control');
                        $email->setAttribute('placeholder', 'Email');

                        $password = $form->get('login_fieldset')->get('Password');
                        $password->setAttribute('class', 'form-control');
                        $password->setAttribute('placeholder', 'Mật khẩu');

                        $form->prepare();
                        echo $this->form()->openTag($form);
                        ?>
                        <small class="form-text text-muted">Cho Demo (testdemo@gmail.com/test@demo123)</small>
                        <div class="form-group">
                            <?= $this->formLabel($email); ?>
                            <?= $this->formElement($email); ?>
                            <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
                        </div>
                        <br />
                        <div class="form-group">
                            <?= $this->formLabel($password); ?>
                            <?= $this->formElement($password); ?>
                            <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
                        </div>
                        <br />
                        <?php
                        echo $this->formRow($form->get('login_fieldset')->get('user_csrf'));
                        echo $this->formSubmit($form->get('submit'));
                        echo "<a class='ms-4' href='/register'>Hoặc Đăng ký tài khoản</a>";
                        echo $this->form()->closeTag();
                        ?>
                    </div>
                </div>
                <div class="col-md-6">
                </div>
            </div>
        </div>
    </div>
</section>