<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
// session_start();
// #du kien luu trong session cac bien sau: KQLogin, TenDN
// if (isset($_SESSION['KQLogin']) == false || $_SESSION['KQLogin'] == false) {
//     #khoi tao gia tri mac dinh cho session
//     $_SESSION['KQLogin'] = false;
//     $_SESSION['TenDN'] = '';
//     header("location:login.php");
//     die;
// }

?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="<?= $this->url('home') ?>">
                    <!-- <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" alt="Laminas">MVC Skeleton -->
                    Nhóm W2-0SS-02
                </a>
            </div>

            <?php if (isset($user)) { ?>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link <?= (str_contains($this->url(), 'lophoc')) ? 'active' : '' ?>"
                            aria-current="page" href="<?= $this->url('lopHoc') ?>">Lớp học
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link <?= (str_contains($this->url(), 'monhoc')) ? 'active' : '' ?>"
                            aria-current="page" href="<?= $this->url('monHoc') ?>">Môn học
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link <?= (str_contains($this->url(), 'hocvien')) ? 'active' : '' ?>"
                            aria-current="page" href="<?= $this->url('hocVien') ?>">Học viên
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link <?= (str_contains($this->url(), 'dangky')) ? 'active' : '' ?>"
                            aria-current="page" href="<?= $this->url('dangKy') ?>">Đăng ký môn
                        </a>
                    </li>
                </ul>
            </div>

            <span class="navbar-text">
                Xin chào,
                <?= $user->Username ?>
                | <a href="<?= $this->url('logout') ?>">
                    Đăng xuất
                </a>
            </span>
            <?php } ?>
        </div>
    </nav>
    <div class="container">
        <?= $this->content ?>
        <hr>
        <footer>
            <p>
                &copy;
                <?= date('Y') ?>
                - Nhóm W2-0SS-02 -
                <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.
            </p>
        </footer>
    </div>
    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/bootstrap.min.js')) ?>
</body>

</html>