<div class="jumbotron">
    <h1><span class="zf-green">Thêm môn học</span></h1>
    <?php
    $maMon = $monHocForm->get('MaMonHoc');
    $maMon->setAttribute('class', 'form-control');
    $maMon->setAttribute('placeholder', 'Mã môn');

    $tenMon = $monHocForm->get('TenMon');
    $tenMon->setAttribute('class', 'form-control');
    $tenMon->setAttribute('placeholder', 'Tên môn');

    $monHocForm->setAttribute('action', $this->url('monHoc', ['action' => 'add']));
    $monHocForm->prepare();
    echo $this->form()->openTag($monHocForm);
    ?>
    <div class="form-group">
        <?= $this->formLabel($maMon); ?>
        <?= $this->formElement($maMon); ?>
        <?= $this->formElementErrors()->render($maMon, ['class' => 'help-block']) ?>
    </div>
    <br/>
    <div class="form-group">
        <?= $this->formLabel($tenMon); ?>
        <?= $this->formElement($tenMon); ?>
        <?= $this->formElementErrors()->render($tenMon, ['class' => 'help-block']) ?>
    </div>
    <br/>
    <?php
    echo $this->formSubmit($monHocForm->get('submit'));
    echo "<a href='javascript:history.go(-1)' class='ms-4 btn btn-outline-secondary'>Quay lại</a>";

    echo $this->form()->closeTag();
    ?>
</div>