<div class="jumbotron">
    <h1><span class="zf-green">Sửa môn học:
            <?= $id ?>
        </span></h1>
    <?php
    $tenMon = $monHocForm->get('TenMon');
    $tenMon->setAttribute('class', 'form-control');
    $tenMon->setAttribute('placeholder', 'Tên môn');

    $monHocForm->setAttribute('action', $this->url(
        'monHoc',
        [
            'action' => 'edit',
            'id' => $id
        ]
    )
    );
    $monHocForm->prepare();
    echo $this->form()->openTag($monHocForm);

    // echo $this->formRow($monHocForm->get('MaMonHoc'));
    echo $this->formHidden($monHocForm->get('MaMonHoc'));
    ?>
    <div class="form-group">
        <?= $this->formLabel($tenMon); ?>
        <?= $this->formElement($tenMon); ?>
        <?= $this->formElementErrors()->render($tenMon, ['class' => 'help-block']) ?>
    </div>
    <br />
    <?php
    echo $this->formSubmit($monHocForm->get('submit'));
    echo "<a href='javascript:history.go(-1)' class='ms-4 btn btn-outline-secondary'>Quay lại</a>";

    echo $this->form()->closeTag();
    ?>
</div>