<div class="jumbotron">
    <h1><span class="zf-green">Sửa đăng ký môn học:
            Mã SV: <?= $dangky->MaSV ?> -
            Lớp: <?= $dangky->Lop ?> (lần học:
            <?= $dangky->LanHocThu ?>)
        </span></h1>
    <?php
    $diem = $dangKyForm->get('Diem');
    $diem->setAttribute('class', 'form-control');
    $diem->setAttribute('placeholder', 'Điểm');

    $dangKyForm->setAttribute(
        'action',
        $this->url(
            'dangKy',
            [
                'action' => 'edit',
                'id' => $id
            ]
        )
    );
    $dangKyForm->prepare();
    echo $this->form()->openTag($dangKyForm);
    ?>
    <?php
    if (isset($messages) && $messages != '') {
        foreach ($messages as $key => $mess_array) {
            $mess_concat = implode(',', $mess_array);
            echo "<p class='alert alert-warning'>$key - $mess_concat</p>";
        }
    }
    ?>
    <?php
    echo $this->formHidden($dangKyForm->get('MaSV'));
    echo $this->formHidden($dangKyForm->get('Lop'));
    echo $this->formHidden($dangKyForm->get('LanHocThu'));
    ?>
    <div class="form-group">
        <?= $this->formLabel($diem); ?>
        <?= $this->formElement($diem); ?>
        <?= $this->formElementErrors()->render($diem, ['class' => 'help-block']) ?>
    </div>
    <br />
    <?php
    echo $this->formSubmit($dangKyForm->get('submit'));
    echo "<a href='javascript:history.go(-1)' class='ms-4 btn btn-outline-secondary'>Quay lại</a>";

    echo $this->form()->closeTag();
    ?>
</div>