<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1><span class="zf-green">Lớp học</span></h1>
    <form method="GET" action="/lophoc">
        <div class="input-group mb-3">
            <input type="text" name="keyword" class="form-control" placeholder="Nhập tên môn hoặc mã lớp để tìm kiếm"
                value="<?= preg_replace('/\s+/', '', $keyword); ?>">
            <div class="input-group-append">
                <input type="submit" name="submit" class="btn btn-primary" value="Tìm">
            </div>
        </div>
    </form>

    <a href="<?= $this->url('lopHoc', ['action' => 'add']) ?>">Thêm</a>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Môn học</th>
                <th scope="col">Lớp</th>
                <th scope="col">Học Kỳ</th>
                <th scope="col">Năm</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>

            <?php foreach ($lopList as $lop): ?>
                <tr>
                    <th scope="row">
                        <?= $this->escapeHtml($lop->tenMon) ?>
                    </th>
                    <td>
                        <?= $this->escapeHtml($lop->maLop) ?>
                    </td>
                    <td>
                        <?= $this->escapeHtml($lop->hocky) ?>
                    </td>
                    <td>
                        <?= $this->escapeHtml($lop->nam) ?>
                    </td>
                    <td>
                        <a href="<?= $this->url('lopHoc', ['action' => 'edit', 'id' => $lop->maLop]) ?>">Edit</a> |
                        <a href="<?= $this->url('lopHoc', ['action' => 'delete', 'id' => $lop->maLop]) ?>">Delete</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>